### ISSUE TITLE
Custom resolve function?

### ISSUE THREAD

**Issue by gitonthescene** [marcwebbie/auto-virtualenv#12]
It might be nice to allow users to override how virtualenv names are [resolved](https://github.com/marcwebbie/auto-virtualenv/blob/master/auto-virtualenv.el#L135).  This would make it easier to adapt to find the virtualenv that say [poetry](https://github.com/python-poetry/poetry) or [nox](https://github.com/theacodes/nox) use.

**Comment by gitonthescene** [comment]
For now just running the following in the shell seems to work to sync up the poetry environment with auto-virtualenv:

``` sh
$ ln -s $(poetry env info -p) .venv
```

**Comment by AmrAwadK** [comment]
Thanks for the tip @gitonthescene ! I found that I also need to restart the server everytime I switch projects using `lsp-workspace-restart` before it picks up the new virtual envionrment, has anyone found a way around this?

**Comment by marcwebbie** [comment]
@AmrAwadK I use a projectile hook to switch virtualenv
