### ISSUE TITLE
Support detection of `venv` folder in project root

### ISSUE THREAD

**Issue by shitikanth** [marcwebbie/auto-virtualenv#9]
It will probably be a good idea to automatically detect and activate the virtualenv in the `venv` folder (besides the `.venv` folder that `auto-virtualenv` is already doing).

**Comment by tilgovi** [comment]
In case it helps you, @shitikanth:

``` elisp
  (defun auto-virtualenv-find-virtualenv-path--more-paths (original-venv-dir)
    "Check additional paths for virtualenv."
    (let* ((project-root (auto-virtualenv--project-root))
          (venv-dir (expand-file-name "venv/" project-root)))
      (cond
       (original-venv-dir original-venv-dir)
       ((file-exists-p venv-dir) venv-dir))))
  (advice-add
   'auto-virtualenv-find-virtualenv-path
   :filter-return
   #'auto-virtualenv-find-virtualenv-path--more-paths)
```

**Comment by ZelphirKaltstahl** [comment]
> In case it helps you, @shitikanth:
> 
>   (defun auto-virtualenv-find-virtualenv-path--more-paths (original-venv-dir)
>     "Check additional paths for virtualenv."
>     (let* ((project-root (auto-virtualenv--project-root))
>           (venv-dir (expand-file-name "venv/" project-root)))
>       (cond
>        (original-venv-dir original-venv-dir)
>        ((file-exists-p venv-dir) venv-dir))))
>   (advice-add
>    'auto-virtualenv-find-virtualenv-path
>    :filter-return
>    #'auto-virtualenv-find-virtualenv-path--more-paths)

This seems to work for me, based on the quoted answer:

``` elisp
(use-package auto-virtualenv
  :ensure t
  :requires python
  :config
  ;; detect folder named venv in project root
  (advice-add
   'auto-virtualenv-find-virtualenv-path
   :filter-return
   (function
    (lambda (original-venv-dir)
      "Check additional paths for virtualenv."
      (let* ((project-root (auto-virtualenv--project-root))
             (venv-dir (expand-file-name "venv/" project-root))
             (venv-dir2 (expand-file-name "dev/venv/" project-root)))
        (cond
         ((file-exists-p venv-dir) venv-dir)
         ((file-exists-p venv-dir2) venv-dir2)
         (original-venv-dir original-venv-dir)
         (t original-venv-dir))))))
  (add-hook 'python-mode-hook 'auto-virtualenv-set-virtualenv)
  ;; Activate on changing buffers
  (add-hook 'window-configuration-change-hook 'auto-virtualenv-set-virtualenv)
  ;; Activate on focus in
  (add-hook 'focus-in-hook 'auto-virtualenv-set-virtualenv))
```

(Using `use-package`.)

Also shows how to add more directories. There is probably a more elegant way using a list of directories, but I was too lazy to work on that, as it seems to cover my needs.
